name: 04 Using Actions
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: Setup Dependencies
              working-directory: 04-using-actions/react-app
              run: |
                npx ci
            - name: Run Unit Test
              working-directory: 04-using-actions/react-app
              run:  |
                npm run test -- --ci