name: 07 using expressions

on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: "[debug] Print start-up Data"
              if: ${{inputs.debug}}
              run: |
                echo "Triggered by: ${{github.ref}}"
                echo "Branch: ${{github.ref_name}}"
                echo "Commit SHA: ${{github.sha}}"
                echo "Runner OS: ${{runner.os}}"
            - name: "[debug] Print when triggered from main"
              if: ${{inputs.debug && github.ref_name == 'refs/heads/develop'}}
              run: |
                echo "Triggered by: ${{github.ref}}"
                echo "Triggered by: ${{github.ref_name}}"
