name: 13 - Using Caching

on: 
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                default: true
                description: Do you want to exec cache step gurl
            node-version:
                type: choice
                options:
                    - 18
                    - 20
                    - 21
                default: "20"
defaults:
    run:
        working-directory: 04-using-actions/react-app 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: ${{inputs.node-version}}
            - name: Download cached dependencies
              id: cache
              if: ${{inputs.use-cache}}
              uses: actions/cache@v4
              with:
                key: deps-node-modules-${{ hashFiles('04-using-actions/react-app/package-lock.json') }}
                path: 04-using-actions/react-app/node_modules
            - name: Install Dependencies
              if: ${{!steps.cache.outputs.cache-hit}}
              run: npm ci
            - name: Testing
              run: npm run test
            - name: Build
              run: npm run build
            - name: Deploy
              run: echo Deploying in nonprod