name: 13 - Using Caching

on: 
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                default: true
                description: Do you want to exec cache step gurl
            node-version:
                type: choice
                options:
                    - 18
                    - 20
                    - 21
                default: "20"
jobs:
    build:
        runs-on: ubuntu-latest
        needs: install-deps
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: ${{inputs.node-version}}
            - name: Download cached dependencies
              id: cache
              if: ${{needs.install-deps.outputs.deps-cache-hit}}
              uses: actions/cache@v4
              with:
                key: deps-node-modules-${{ hashFiles('04-using-actions/react-app/package-lock.json') }}
                path: 04-using-actions/react-app/node_modules
            - name: Testing
              run: npm run test
            - name: Build
              run: npm run build
            - name: Deploy
              run: echo Deploying in nonprod
    install-deps:
        defaults:
            run:
                working-directory: 04-using-actions/react-app
        runs-on: ubuntu-latest
        outputs:
          deps-cache-hit: ${{steps.cache-key.outputs.CACHE_KEY}}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: ${{inputs.node-version}}
            - name: Calculate cache key
              id: cache-key
              run: |
                echo CACHE_KEY=deps-node-modules-${{ hashFiles('04-using-actions/react-app/package-lock.json') }} >> $GITHUB_OUPUT
            - name: Download cache hit
              uses: actions/cache@v4
              id: cache
              with:
                key: ${{steps.cache-key.outputs.CACHE_KEY}}
                path: 04-using-actions/react-app/node_modules
            - name: Install Dependencies
              if: ${{steps.cache.outputs.cache-hit}}
              run: npm ci
    lintint:
        runs-on: ubuntu-latest
        needs: install-deps
        defaults:
          run:
            working-directory: 04-using-actions/react-app
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
          - name: Setup Node
            uses: actions/setup-node@v4
            with:
              node-version: ${{inputs.node-version}}
          - name: Download cache hit
            uses: actions/cache@v4
            id: cache
            with:
              key: ${{needs.install-deps.outputs.deps-cache-hit}}
              path: 04-using-actions/react-app/node_modules
          - name: Testing
            run: npm run test
          - name: Listing
            run: echo Linting
          