name: 14 Working with Artifacts v2

on:
    workflow_dispatch:

jobs:
    test-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/react-app
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: "20.x"
            - name: Download cache dependencies
              uses: actions/cache@v4
              id: cache
              with:
                key: deps-node-modules-${{hashFiles('04-using-actions/react-app/package-lock.json')}}
                path: 04-using-actions/react-app/node_modules
            - name: Install Dependencies
              if: ${{!steps.cache.outputs.cache-hit}}
              run: npm ci
            - name: Unit Test
              run: npm run test
            - name: Build
              run: npm run build
            - name: Upload Files
              uses: actions/upload-artifact@v4
              with:
                name: app
                path: 04-using-actions/react-app/build
    deploy:
        runs-on: ubuntu-latest
        needs: test-build
        steps:
            - name: Download build files
              uses: actions/download-artifact@v4
              with:
                name: app
                path: build
