name: 16 Working with environments
run-name: 16 Working with environments Env - ${{inputs.target_env}}
on:
    workflow_dispatch:
        inputs:
            target_env:
                type: environment
                default: staging
jobs:
    e2e-testing:
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - name: Just For Fun
              run: echo Running tests
    deploy-staging:
        runs-on: ubuntu-latest
        needs: e2e-testing
        environment: staging
        env: 
            var-b: ${{vars.MY_ENV_VALUE||'NOT FOUND'}}
        steps:
            - name: Just For Fun
              run: echo Printing the var ${{env.var-b}}
    deploy-prod:
        runs-on: ubuntu-latest
        needs: deploy-staging
        environment: prod
        env: 
            var-b: ${{vars.MY_ENV_VALUE||'NOT FOUND'}}
        steps:
            - name: Just For Fun
              run: echo Printing the var ${{env.var-b}}
    